server {
    listen 10.12.1.1:9999;                # Host
    server_name example.com;        # Server name
    
    error_page 404 www/error/404.html;
    client_max_body_size 10M;       # Limit for uploads

    # Main route
    location / {
        root www/;
        index index.html;
        autoindex on;               # Turn on directory listing
    }

    # Upload directory
    location /uploads {
        root www/uploads;
    }

 
}

