server {
    listen 8080;
    server_name localhost;
    root tester_root;
    client_max_body_size 100m;

    location / {
        index index.html;
        limit_except GET {
            deny all;
        }
    }

    # Match /directory and /directory/
    location /directory {
        root tester_root; 

        index youpi.bad_extension;
        limit_except GET {
            deny all;
        }
    }

    location /post_body {
        limit_except POST {
            deny all;
        }
        client_max_body_size 100;
    }

    location .bla {
        cgi_pass .bla ./cgi_test;
        limit_except POST {
            deny all;
        }
    }
}